//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace HealthCare.WebService.BJFC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AddOrdInfoServiceSoap", Namespace="http://tempuri.org")]
    public partial class AddOrdInfoService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddOrdInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPatInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendDeptnfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendDrugDicInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendTarItemInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendUserInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AddOrdInfoService() {
            this.Url = global::HealthCare.WebService.Properties.Settings.Default.HealthCare_WebService_BJFC_AddOrdInfoService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddOrdInfoCompletedEventHandler AddOrdInfoCompleted;
        
        /// <remarks/>
        public event GetPatInfoCompletedEventHandler GetPatInfoCompleted;
        
        /// <remarks/>
        public event SendDeptnfoCompletedEventHandler SendDeptnfoCompleted;
        
        /// <remarks/>
        public event SendDrugDicInfoCompletedEventHandler SendDrugDicInfoCompleted;
        
        /// <remarks/>
        public event SendTarItemInfoCompletedEventHandler SendTarItemInfoCompleted;
        
        /// <remarks/>
        public event SendUserInfoCompletedEventHandler SendUserInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DHC.ZNYG.BS.AddOrdInfo.AddOrdInfo", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddOrdInfo(string Input) {
            object[] results = this.Invoke("AddOrdInfo", new object[] {
                        Input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddOrdInfoAsync(string Input) {
            this.AddOrdInfoAsync(Input, null);
        }
        
        /// <remarks/>
        public void AddOrdInfoAsync(string Input, object userState) {
            if ((this.AddOrdInfoOperationCompleted == null)) {
                this.AddOrdInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOrdInfoOperationCompleted);
            }
            this.InvokeAsync("AddOrdInfo", new object[] {
                        Input}, this.AddOrdInfoOperationCompleted, userState);
        }
        
        private void OnAddOrdInfoOperationCompleted(object arg) {
            if ((this.AddOrdInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddOrdInfoCompleted(this, new AddOrdInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DHC.ZNYG.BS.AddOrdInfo.GetPatInfo", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPatInfo(string Input) {
            object[] results = this.Invoke("GetPatInfo", new object[] {
                        Input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPatInfoAsync(string Input) {
            this.GetPatInfoAsync(Input, null);
        }
        
        /// <remarks/>
        public void GetPatInfoAsync(string Input, object userState) {
            if ((this.GetPatInfoOperationCompleted == null)) {
                this.GetPatInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPatInfoOperationCompleted);
            }
            this.InvokeAsync("GetPatInfo", new object[] {
                        Input}, this.GetPatInfoOperationCompleted, userState);
        }
        
        private void OnGetPatInfoOperationCompleted(object arg) {
            if ((this.GetPatInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPatInfoCompleted(this, new GetPatInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DHC.ZNYG.BS.AddOrdInfo.SendDeptnfo", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendDeptnfo(string Input) {
            object[] results = this.Invoke("SendDeptnfo", new object[] {
                        Input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendDeptnfoAsync(string Input) {
            this.SendDeptnfoAsync(Input, null);
        }
        
        /// <remarks/>
        public void SendDeptnfoAsync(string Input, object userState) {
            if ((this.SendDeptnfoOperationCompleted == null)) {
                this.SendDeptnfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendDeptnfoOperationCompleted);
            }
            this.InvokeAsync("SendDeptnfo", new object[] {
                        Input}, this.SendDeptnfoOperationCompleted, userState);
        }
        
        private void OnSendDeptnfoOperationCompleted(object arg) {
            if ((this.SendDeptnfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendDeptnfoCompleted(this, new SendDeptnfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DHC.ZNYG.BS.AddOrdInfo.SendDrugDicInfo", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendDrugDicInfo(string Input) {
            object[] results = this.Invoke("SendDrugDicInfo", new object[] {
                        Input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendDrugDicInfoAsync(string Input) {
            this.SendDrugDicInfoAsync(Input, null);
        }
        
        /// <remarks/>
        public void SendDrugDicInfoAsync(string Input, object userState) {
            if ((this.SendDrugDicInfoOperationCompleted == null)) {
                this.SendDrugDicInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendDrugDicInfoOperationCompleted);
            }
            this.InvokeAsync("SendDrugDicInfo", new object[] {
                        Input}, this.SendDrugDicInfoOperationCompleted, userState);
        }
        
        private void OnSendDrugDicInfoOperationCompleted(object arg) {
            if ((this.SendDrugDicInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendDrugDicInfoCompleted(this, new SendDrugDicInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DHC.ZNYG.BS.AddOrdInfo.SendTarItemInfo", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendTarItemInfo(string Input) {
            object[] results = this.Invoke("SendTarItemInfo", new object[] {
                        Input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendTarItemInfoAsync(string Input) {
            this.SendTarItemInfoAsync(Input, null);
        }
        
        /// <remarks/>
        public void SendTarItemInfoAsync(string Input, object userState) {
            if ((this.SendTarItemInfoOperationCompleted == null)) {
                this.SendTarItemInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendTarItemInfoOperationCompleted);
            }
            this.InvokeAsync("SendTarItemInfo", new object[] {
                        Input}, this.SendTarItemInfoOperationCompleted, userState);
        }
        
        private void OnSendTarItemInfoOperationCompleted(object arg) {
            if ((this.SendTarItemInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendTarItemInfoCompleted(this, new SendTarItemInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DHC.ZNYG.BS.AddOrdInfo.SendUserInfo", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendUserInfo(string Input) {
            object[] results = this.Invoke("SendUserInfo", new object[] {
                        Input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendUserInfoAsync(string Input) {
            this.SendUserInfoAsync(Input, null);
        }
        
        /// <remarks/>
        public void SendUserInfoAsync(string Input, object userState) {
            if ((this.SendUserInfoOperationCompleted == null)) {
                this.SendUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendUserInfoOperationCompleted);
            }
            this.InvokeAsync("SendUserInfo", new object[] {
                        Input}, this.SendUserInfoOperationCompleted, userState);
        }
        
        private void OnSendUserInfoOperationCompleted(object arg) {
            if ((this.SendUserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendUserInfoCompleted(this, new SendUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AddOrdInfoCompletedEventHandler(object sender, AddOrdInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddOrdInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddOrdInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetPatInfoCompletedEventHandler(object sender, GetPatInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPatInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPatInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SendDeptnfoCompletedEventHandler(object sender, SendDeptnfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendDeptnfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendDeptnfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SendDrugDicInfoCompletedEventHandler(object sender, SendDrugDicInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendDrugDicInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendDrugDicInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SendTarItemInfoCompletedEventHandler(object sender, SendTarItemInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendTarItemInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendTarItemInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SendUserInfoCompletedEventHandler(object sender, SendUserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591