Dism /online /Enable-Feature /FeatureName:NetFx4ServerFeatures /All
Dism /online /Enable-Feature /FeatureName:NetFx4 /All
Dism /online /Enable-Feature /FeatureName:NetFx4Extended-ASPNET45 /All
Dism /online /Enable-Feature /FeatureName:MicrosoftWindowsPowerShellRoot /All
Dism /online /Enable-Feature /FeatureName:MicrosoftWindowsPowerShell /All
Dism /online /Enable-Feature /FeatureName:MicrosoftWindowsPowerShellV2 /All
Dism /online /Enable-Feature /FeatureName:Server-Psh-Cmdlets /All
Dism /online /Enable-Feature /FeatureName:MicrosoftWindowsPowerShellISE /All
Dism /online /Enable-Feature /FeatureName:IIS-WebServerRole /All
Dism /online /Enable-Feature /FeatureName:IIS-WebServer /All
Dism /online /Enable-Feature /FeatureName:IIS-CommonHttpFeatures /All
Dism /online /Enable-Feature /FeatureName:IIS-Security /All
Dism /online /Enable-Feature /FeatureName:IIS-RequestFiltering /All
Dism /online /Enable-Feature /FeatureName:IIS-StaticContent /All
Dism /online /Enable-Feature /FeatureName:IIS-DefaultDocument /All
Dism /online /Enable-Feature /FeatureName:IIS-DirectoryBrowsing /All
Dism /online /Enable-Feature /FeatureName:IIS-HttpErrors /All
Dism /online /Enable-Feature /FeatureName:IIS-HttpRedirect /All
Dism /online /Enable-Feature /FeatureName:IIS-ApplicationDevelopment /All
Dism /online /Enable-Feature /FeatureName:IIS-WebSockets /All
Dism /online /Enable-Feature /FeatureName:IIS-NetFxExtensibility /All
Dism /online /Enable-Feature /FeatureName:IIS-NetFxExtensibility45 /All
Dism /online /Enable-Feature /FeatureName:IIS-ISAPIExtensions /All
Dism /online /Enable-Feature /FeatureName:IIS-ISAPIFilter /All
Dism /online /Enable-Feature /FeatureName:IIS-ASPNET45 /All
Dism /online /Enable-Feature /FeatureName:IIS-ServerSideIncludes /All
Dism /online /Enable-Feature /FeatureName:IIS-HealthAndDiagnostics /All
Dism /online /Enable-Feature /FeatureName:IIS-HttpLogging /All
Dism /online /Enable-Feature /FeatureName:IIS-Performance /All
Dism /online /Enable-Feature /FeatureName:IIS-HttpCompressionStatic /All
Dism /online /Enable-Feature /FeatureName:IIS-HttpCompressionDynamic /All
Dism /online /Enable-Feature /FeatureName:IIS-WebServerManagementTools /All
Dism /online /Enable-Feature /FeatureName:IIS-ManagementConsole /All
Dism /online /Enable-Feature /FeatureName:WAS-WindowsActivationService /All
Dism /online /Enable-Feature /FeatureName:WAS-ProcessModel /All
Dism /online /Enable-Feature /FeatureName:WAS-NetFxEnvironment /All
Dism /online /Enable-Feature /FeatureName:WAS-ConfigurationAPI /All
Dism /online /Enable-Feature /FeatureName:IIS-HostableWebCore /All
Dism /online /Enable-Feature /FeatureName:WCF-Services45 /All
Dism /online /Enable-Feature /FeatureName:WCF-TCP-PortSharing45 /All
Dism /online /Enable-Feature /FeatureName:WCF-HTTP-Activation /All
Dism /online /Enable-Feature /FeatureName:WCF-NonHTTP-Activation /All
Dism /online /Enable-Feature /FeatureName:ServerCore-WOW64 /All
Dism /online /Enable-Feature /FeatureName:ServerCore-EA-IME-WOW64 /All
Dism /online /Enable-Feature /FeatureName:NetFx3ServerFeatures /All
Dism /online /Enable-Feature /FeatureName:NetFx3 /All
Dism /online /Enable-Feature /FeatureName:Server-Shell /All
Dism /online /Enable-Feature /FeatureName:Internet-Explorer-Optional-amd64 /All
Dism /online /Enable-Feature /FeatureName:WindowsServerBackupSnapin /All
Dism /online /Enable-Feature /FeatureName:Microsoft-Hyper-V-Common-Drivers-Package /All
Dism /online /Enable-Feature /FeatureName:Microsoft-Hyper-V-Guest-Integration-Drivers-Package /All
Dism /online /Enable-Feature /FeatureName:Microsoft-Windows-NetFx-VCRedist-Package /All
Dism /online /Enable-Feature /FeatureName:Microsoft-Windows-Client-EmbeddedExp-Package /All
Dism /online /Enable-Feature /FeatureName:ServerCore-EA-IME /All
Dism /online /Enable-Feature /FeatureName:Server-Drivers-General /All
Dism /online /Enable-Feature /FeatureName:Server-Drivers-Printers /All
Dism /online /Enable-Feature /FeatureName:FileAndStorage-Services /All
Dism /online /Enable-Feature /FeatureName:Storage-Services /All
Dism /online /Enable-Feature /FeatureName:ServerCore-Drivers-General /All
Dism /online /Enable-Feature /FeatureName:ServerCore-Drivers-General-WOW64 /All
Dism /online /Disable-Feature /FeatureName:IIS-WebDAV
pause